trakt:
  account: syl
  series: series
  movies: watchlist
  ended: ended

rss:
  series: https://showrss.info/user/11917.rss?magnets=true&namespaces=false&name=null&quality=null&re=null
  anime: http://www.shanaproject.com/feeds/secure/user/40150/7OYOS9PO5F/

folder:
### path of the folder/mountpoint for all the media, without the leading slash
  root: /Elements/
### media and download paths, relative to the previous path
  series: series/
  anime: anime/
  movies: movies/
  downseries: downloads/series/
  downanime: downloads/anime/
  downmovies: downloads/movies/
transmission:
  host: transmission
  user: transmission
  pass: transmission
kodi:
  host: http://192.168.2.8
opensubtitles:
  user: user
  password: password
addic7ed:
  user: user
  password: password
